fix bugs

diff --git a/luci-app-openclash/root/etc/init.d/openclash b/luci-app-openclash/root/etc/init.d/openclash
--- a/luci-app-openclash/root/etc/init.d/openclash
+++ b/luci-app-openclash/root/etc/init.d/openclash
@@ -903,35 +903,6 @@ yml_custom_rule_provider()
 
 }
 
-ac_add()
-{
-   if [ -z "$1" ]; then
-      return
-   fi
-  
-   ipset add "$2" "$1" 2>/dev/null
-}
-
-firewall_redirect_exclude()
-{
-   local section="$1"
-   local src_dport
-   config_get "src_dport" "$section" "src_dport" ""
-   
-   if [ -z "$src_dport" ]; then
-      return
-   fi
-   
-   if [ -z "$en_mode_tun" ]; then
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-   elif [ "$en_mode_tun" -ne 3 ]; then
-      iptables -t mangle -A openclash -p tcp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-   else
-      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
-   fi
-}
-
 #配置文件选择
 config_choose()
 {
@@ -1111,6 +1082,150 @@ start_run_core()
    fi
    uci set openclash.config.config_reload=1 2>/dev/null
    uci commit openclash
+}
+
+check_core_status()
+{
+   check_time=1
+   while ( [ "$check_time" -le 3 ] && [ -z "$(pidof clash)" ] )
+   do
+      sleep 2
+      check_time=$(expr "$check_time" + 1)
+   done
+}
+
+#不修改配置文件启动
+raw_config_start()
+{
+   mv "$START_BACKUP" "$CONFIG_FILE"
+   dns_port=$(grep "^ \{0,\}listen:" "$CONFIG_FILE" |awk -F ':' '{print $3}' |awk -F '#' '{print $1}' |tr -cd "[0-9]" 2>/dev/null)
+   en_mode=$(grep "^ \{0,\}enhanced-mode:" "$CONFIG_FILE" |awk -F ': ' '{print $2}' |awk -F '#' '{print $1}' 2>/dev/null |sed 's/^ \{0,\}//g' 2>/dev/null |sed 's/ \{0,\}$//g' 2>/dev/null)
+   proxy_port=$(grep "^ \{0,\}redir-port:" "$CONFIG_FILE" |awk -F ': ' '{print $2}' |awk -F '#' '{print $1}' 2>/dev/null |tr -cd "[0-9]")
+   
+   if [ -z "$dns_port" ] || [ -z "$en_mode" ] || [ -z "$proxy_port" ]; then
+      echo "错误: 无法获取General部分的必要设置, OpenClash 使用原始配置文件启动失败" >$START_LOG
+      echo "${LOGTIME} Incomplete Config, OpenClash Can Not Start With Raw Config File" >> $LOG_FILE
+      start_fail
+   fi
+   
+   start_run_core
+   check_core_status
+   
+   if ! pidof clash >/dev/null; then
+      echo "错误: OpenClash 启动失败，请到日志页面查看详细错误信息！" >$START_LOG
+      echo "${LOGTIME} OpenClash Can Not Start, Please Check The Error Info And Try Again" >> $LOG_FILE
+      start_fail
+   fi
+   
+   if [ "$en_mode" = "redir-host" ]; then
+      case $en_mode_tun in
+      "1")
+         uci set openclash.config.en_mode=redir-host-tun
+      ;;
+      "2")
+         uci set openclash.config.en_mode=redir-host-vpn
+      ;;
+      "3")
+         uci set openclash.config.en_mode=redir-host-mix
+      ;;
+      *)
+         uci set openclash.config.en_mode=redir-host
+      esac
+   elif [ "$en_mode" = "fake-ip" ]; then
+   	  case $en_mode_tun in
+      "1")
+         uci set openclash.config.en_mode=fake-ip-tun
+      ;;
+      "2")
+         uci set openclash.config.en_mode=fake-ip-vpn
+      ;;
+      "3")
+         uci set openclash.config.en_mode=fake-ip-mix
+      ;;
+      *)
+         uci set openclash.config.en_mode=fake-ip
+      esac
+   fi
+   
+   dase=$(grep "^ \{0,\}Secret:" "$CONFIG_FILE" |awk -F ': ' '{print $2}' |awk -F '#' '{print $1}' |sed 's/^ \{0,\}//g' 2>/dev/null |sed 's/ \{0,\}$//g' 2>/dev/null |sed "s/\'//g" 2>/dev/null |sed "s/\'//g" 2>/dev/null)
+   uci set openclash.config.dashboard_password=dase 2>/dev/null
+   
+   cn_port=$(grep "^ \{0,\}external-controller:" "$CONFIG_FILE" |awk -F ':' '{print $3}' |awk -F '#' '{print $1}' |tr -cd "[0-9]" 2>/dev/null)
+   uci set openclash.config.dashboard_password=cn_port 2>/dev/null
+   
+   uci set openclash.config.restricted_mode=1
+   
+   uci commit openclash
+}
+
+try_restore_start()
+{
+   if [ -z "$(pidof clash)" ]; then
+      if [ "$rule_source" = 0 ] && [ "$enable_custom_clash_rules" = 0 ]; then
+         echo "错误: OpenClash 启动失败，尝试使用原始配置文件启动..." >$START_LOG
+         echo "${LOGTIME} OpenClash Can Not Start, Try Use Raw Config Restart Again" >> $LOG_FILE
+         sleep 3
+         raw_config_start
+      else
+         echo "错误: OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序..." >$START_LOG
+         echo "${LOGTIME} OpenClash Can Not Start, Try Use Backup Rules Start Again" >> $LOG_FILE
+         rm -rf /tmp/yaml_general 2>/dev/null
+         #获取备份rule_provider
+         rule_provider_bak_len=$(sed -n '/^rule-providers:/=' "$START_BACKUP" 2>/dev/null)
+         if [ -n "$rule_provider_bak_len" ]; then
+            /usr/share/openclash/yml_field_cut.sh "$rule_provider_bak_len" "$RULE_PROVIDER_BAK_FILE" "$START_BACKUP"
+         fi 2>/dev/null
+         #获取备份script
+         script_bak_len=$(sed -n '/^script:/=' "$START_BACKUP" 2>/dev/null)
+         if [ -n "$script_bak_len" ]; then
+            /usr/share/openclash/yml_field_cut.sh "$script_bak_len" "$SCRIPT_BAK_FILE" "$START_BACKUP"
+         fi 2>/dev/null
+         #获取备份rule
+         rule_bak_len=$(sed -n '/^rules:/=' "$START_BACKUP" 2>/dev/null)
+         if [ -n "$rule_bak_len" ]; then
+            /usr/share/openclash/yml_field_cut.sh "$rule_bak_len" "$RULE_BAK_FILE" "$START_BACKUP"
+         fi 2>/dev/null
+         yml_rule_bak_merge
+         nohup "$CLASH" -d "$CLASH_CONFIG" -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
+         check_core_status
+         if ! pidof clash >/dev/null; then
+            echo "错误: OpenClash 启动失败，尝试使用原始配置文件启动..." >$START_LOG
+            echo "${LOGTIME} OpenClash Can Not Start, Try Use Raw Config Restart Again" >> $LOG_FILE
+            sleep 3
+            raw_config_start
+         fi
+      fi
+   fi
+}
+
+#防火墙设置部分
+ac_add()
+{
+   if [ -z "$1" ]; then
+      return
+   fi
+  
+   ipset add "$2" "$1" 2>/dev/null
+}
+
+firewall_redirect_exclude()
+{
+   local section="$1"
+   local src_dport
+   config_get "src_dport" "$section" "src_dport" ""
+   
+   if [ -z "$src_dport" ]; then
+      return
+   fi
+   
+   if [ -z "$en_mode_tun" ]; then
+      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+   elif [ "$en_mode_tun" -ne 3 ]; then
+      iptables -t mangle -A openclash -p tcp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+   else
+      iptables -t mangle -A openclash -p udp --dport "$src_dport" -j RETURN >/dev/null 2>&1
+   fi
 }
 
 set_firewall()
@@ -1462,29 +1577,7 @@ get_config()
    stack_type=$(uci get openclash.config.stack_type 2>/dev/null)
    china_ip_route=$(uci get openclash.config.china_ip_route 2>/dev/null)
    small_flash_memory=$(uci get openclash.config.small_flash_memory 2>/dev/null)
-}
-
-yml_field_check()
-{
-   if [ -f "$GROUP_FILE" ]; then
-      if [ ! -f "$PROXY_FILE" ] && [ ! -f "$PROXY_PROVIDER_FILE" ]; then
-         echo "错误: 配置文件完整性检查不通过，已自动还原配置文件，请对照模板格式检查修改配置文件！" >$START_LOG
-         mv "$START_BACKUP" "$CONFIG_FILE"
-         sleep 5
-         start_fail
-      elif [ ! -f "$RULE_FILE" ] && [ ! -f "$SCRIPT_FILE" ]; then
-         echo "错误: 配置文件完整性检查不通过，已自动还原配置文件，请对照模板格式检查修改配置文件！" >$START_LOG
-         mv "$START_BACKUP" "$CONFIG_FILE"
-         sleep 5
-         start_fail
-      fi
-   else
-      nohup "$CLASH" -d "$CLASH_CONFIG" -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
-      echo "错误: 配置文件完整性检查不通过，已自动还原配置文件，请根据日志信息对照模板格式检查修改配置文件！" >$START_LOG
-      mv "$START_BACKUP" "$CONFIG_FILE"
-      sleep 5
-      start_fail
-   fi
+   uci set openclash.config.restricted_mode=0 && uci commit openclash
 }
 
 start()
@@ -1510,7 +1603,6 @@ start()
    echo "第二步: 配置文件检查..." >$START_LOG
    yml_check "$en_mode" "$enable_custom_dns" "$CONFIG_FILE" "$BACKUP_FILE" "$START_BACKUP"
    yml_dns_check
-   yml_field_check
    
    echo "第三步: 修改配置文件..." >$START_LOG
    config_load "openclash"
@@ -1543,66 +1635,38 @@ start()
    echo "第六步: 等待主程序下载外部文件..." >$START_LOG
    yml_provider_check "$PROXY_PROVIDER_FILE" "proxy_provider"
    yml_provider_check "$RULE_PROVIDER_FILE" "rule_provider"
-
-   echo "第七步: 设置控制面板..." >$START_LOG
+   
+   echo "第七步: 检查内核启动状态..." >$START_LOG
+   check_core_status
+   try_restore_start
+   
+   echo "第八步: 设置控制面板..." >$START_LOG
    ln -s /usr/share/openclash/yacd /www/luci-static/openclash 2>/dev/null
        
-   echo "第八步: 设置防火墙规则..." >$START_LOG
+   echo "第九步: 设置防火墙规则..." >$START_LOG
    set_firewall
 
-   echo "第九步: 重启 Dnsmasq 程序..." >$START_LOG
+   echo "第十步: 重启 Dnsmasq 程序..." >$START_LOG
    change_dns "$enable_redirect_dns" "$disable_masq_cache"
    /etc/init.d/dnsmasq restart >/dev/null 2>&1
-   
-   echo "第十步: 检查内核启动状态..." >$START_LOG
-   if [ -z "$(pidof clash)" ] && [ "$rule_source" = 0 ] && [ "$enable_custom_clash_rules" = 0 ]; then
-      echo "错误: OpenClash 启动失败，请到日志页面查看详细错误信息！" >$START_LOG
-      echo "${LOGTIME} OpenClash Can Not Start, Please Check The Error Info And Try Again" >> $LOG_FILE
-      sleep 5
-      start_fail
-   fi
-   if ! pidof clash >/dev/null; then
-      echo "错误: OpenClash 启动失败，尝试还原第三方规则并重新启动 Clash 主程序..." >$START_LOG
-      echo "${LOGTIME} OpenClash Can Not Start, Try Use Backup Rules Start Again" >> $LOG_FILE
-      rm -rf /tmp/yaml_general 2>/dev/null
-      #获取备份rule_provider
-      rule_provider_bak_len=$(sed -n '/^rule-providers:/=' "$START_BACKUP" 2>/dev/null)
-      if [ -n "$rule_provider_bak_len" ]; then
-         /usr/share/openclash/yml_field_cut.sh "$rule_provider_bak_len" "$RULE_PROVIDER_BAK_FILE" "$START_BACKUP"
-      fi 2>/dev/null
-      #获取备份script
-      script_bak_len=$(sed -n '/^script:/=' "$START_BACKUP" 2>/dev/null)
-      if [ -n "$script_bak_len" ]; then
-         /usr/share/openclash/yml_field_cut.sh "$script_bak_len" "$SCRIPT_BAK_FILE" "$START_BACKUP"
-      fi 2>/dev/null
-      #获取备份rule
-      rule_bak_len=$(sed -n '/^rules:/=' "$START_BACKUP" 2>/dev/null)
-      if [ -n "$rule_bak_len" ]; then
-         /usr/share/openclash/yml_field_cut.sh "$rule_bak_len" "$RULE_BAK_FILE" "$START_BACKUP"
-      fi 2>/dev/null
-      yml_rule_bak_merge
-      nohup "$CLASH" -d "$CLASH_CONFIG" -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
-      sleep 3
-      if ! pidof clash >/dev/null; then
-         echo "错误: OpenClash 启动失败，请到日志页面查看详细错误信息！" >$START_LOG
-         echo "${LOGTIME} OpenClash Can Not Start, Please Check The Error Info And Try Again" >> $LOG_FILE
-         sleep 5
-         start_fail
-      fi
-   fi
             
    echo "第十一步: 还原策略组节点状态..." >$START_LOG
    /usr/share/openclash/openclash_history_set.sh
    
    echo "第十二步: 添加计划任务,启动进程守护程序..." >$START_LOG
    add_cron
-   if [ -z "$(uci get dhcp.lan.dhcpv6 2>/dev/null)" ]; then
+   if [ -z "$(uci get dhcp.lan.dhcpv6 2>/dev/null)" ] && [ "$(uci get openclash.config.restricted_mode 2>/dev/null)" != "1" ]; then
       echo "OpenClash 启动成功，请等待服务器上线！" >$START_LOG
       echo "${LOGTIME} OpenClash Start Successful" >> $LOG_FILE
       sleep 5
-   else
+   elif [ -n "$(uci get dhcp.lan.dhcpv6 2>/dev/null)" ]; then
       echo "OpenClash 启动成功，检测到您启用了IPV6的DHCP服务，可能会造成连接异常！" >$START_LOG
       echo "${LOGTIME} OpenClash Start Successful, Please Note That Network May Abnormal With IPV6's DHCP Server" >> $LOG_FILE
+      sleep 5
+   fi
+   if [ "$(uci get openclash.config.restricted_mode 2>/dev/null)" = "1" ]; then
+      echo "OpenClash 使用原始配置文件启动成功，部分设置可能未生效！" >$START_LOG
+      echo "${LOGTIME} OpenClash Start Successful With Raw Config File, Please Note That It's Restricted Mode Now" >> $LOG_FILE
       sleep 5
    fi
    echo "OpenClash Already Start"
