change: restore all the change in config file and try restart final

diff --git a/luci-app-openclash/root/etc/init.d/openclash b/luci-app-openclash/root/etc/init.d/openclash
--- a/luci-app-openclash/root/etc/init.d/openclash
+++ b/luci-app-openclash/root/etc/init.d/openclash
@@ -1554,14 +1554,22 @@ start()
       yml_rule_bak_merge
       nohup "$CLASH" -d "$CLASH_CONFIG" -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
       sleep 3
+
       if ! pidof clash >/dev/null; then
-         echo "错误: OpenClash 启动失败，请到日志页面查看详细错误信息！" >$START_LOG
-         echo "${LOGTIME} OpenClash Can Not Start, Please Check The Error Info And Try Again" >> $LOG_FILE
-         sleep 5
-         start_fail
+         echo "错误: 尝试还原第三方规则并重新启动失败，还原配置文件改动并重新启动..." >$START_LOG
+         echo "${LOGTIME} Try Use Backup Rules Start Faild, Restore Config File And Restart..." >> $LOG_FILE
+         cp $START_BACKUP $CONFIG_FILE 2>/dev/null
+         nohup "$CLASH" -d "$CLASH_CONFIG" -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
+         sleep 3
+         if ! pidof clash >/dev/null; then
+            echo "错误: OpenClash 启动失败，请到日志页面查看详细错误信息！" >$START_LOG
+            echo "${LOGTIME} OpenClash Can Not Start, Please Check The Error Info And Try Again" >> $LOG_FILE
+            sleep 5
+            start_fail
+         fi
       fi
    fi
-            
+
    echo "第十一步: 还原策略组节点状态..." >$START_LOG
    /usr/share/openclash/openclash_history_set.sh
    
